clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  tests:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export COURSIER_CACHE='/workdir/coursier/'
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - git clone https://github.com/mytimecoin/scala-abci-server.git scala-abci-server --depth 1
      - cd /workdir/code/scala-abci-server && sbt $SBT_OPTS publishLocal
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 scalafmtCheck scalafixTest test
  package:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export COURSIER_CACHE='/workdir/coursier/'
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code/scala-abci-server && sbt $SBT_OPTS publishLocal
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 cli/universal:packageBin cli/universal:stage
    when:
      event: tag
  build-win-installer:
    image: gcr.io/time-coin/wix-builder:0.2
    environment:
      - PRAVDA_VERSION=${DRONE_TAG##v}
    commands:
      - cp -rf /workdir/code/cli/target/universal/stage /workdir/code/win-installer/
      - cd /workdir/code/win-installer && bash build.sh
      - mv /workdir/code/cli/target/universal/*.zip /workdir/code/cli/target/universal/PravdaSDK-$$PRAVDA_VERSION.zip
    when:
      event: tag
  release:
    image: plugins/github-release
    files:
      - /workdir/code/win-installer/*.msi
      - /workdir/code/cli/target/universal/*.zip
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
