clone:
  clone:
    image: plugins/git
    tags: true
workspace:
  base: /workdir
  path: code
pipeline:
  tests:
    image: gcr.io/time-coin/sbt:latest
    pull: true
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export COURSIER_CACHE='/workdir/coursier/'
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 headerCheck scalafmtCheck test:scalafmtCheck test "gen-doc/run --check"
  package-zip:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/coursier-cache:/workdir/coursier
    commands:
      - export COURSIER_CACHE='/workdir/coursier/'
      - export SBT_OPTS='-Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code && sbt $SBT_OPTS -mem 2048 cli/universal:packageZipTarball cli/universal:stage node/docker:stage
    when:
      event: tag
  package-msi:
    image: gcr.io/time-coin/wix-builder:0.2
    environment:
      - PRAVDA_VERSION=${DRONE_TAG}
    commands:
      - cp -rf /workdir/code/cli/target/universal/stage /workdir/code/win-installer/
      - cd /workdir/code/win-installer && bash build.sh
      - mv /workdir/code/cli/target/universal/*.tgz /workdir/code/cli/target/universal/PravdaSDK-$$PRAVDA_VERSION.tgz
    when:
      event: tag
  package-publish-nuget:
    image: microsoft/dotnet:2.1-sdk
    environment:
      - PRAVDA_VERSION=${DRONE_TAG##v}
    commands:
      - cd /workdir/code/PravdaDotNet
      - dotnet pack -c Release
      - dotnet nuget push bin/Release/Pravda.$PRAVDA_VERSION.nupkg -ApiKey $NUGET_KEY -Source https://api.nuget.org/v3/index.json      
    when:
      event: tag
  publish-github-releases:
    image: plugins/github-release
    files:
      - /workdir/code/win-installer/*.msi
      - /workdir/code/cli/target/universal/*.tgz
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
  publish-docker:
    image: plugins/docker
    repo: expload/pravda
    context: /workdir/code/node/target/docker/stage/
    dockerfile: /workdir/code/node/target/docker/stage/Dockerfile
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    when:
      event: tag
